language: cpp
dist: bionic
compiler: gcc

install: 
  - sudo apt update -qq
  # Boost
  - sudo apt install -qq libboost-all-dev
  # LyX
  - sudo add-apt-repository -y ppa:lyx-devel/release
  - sudo apt-get update -qq
  - sudo apt-get install lyx

script:
  - lyx --export pdf travis_lyx.lyx
  - if [ ! -e travis_lyx.pdf ]; then exit 1; fi