language: cpp
dist: bionic

install: 
  - sudo apt update -qq
  # Boost
  - sudo apt install -qq libboost-all-dev
  # LyX
  - sudo add-apt-repository -y ppa:lyx-devel/release
  - sudo apt-get update -qq
  - sudo apt-get install lyx

script:
  - lyx --export pdf travis_lyx.lyx
  - if [ ! -e travis_lyx.pdf ]; then exit 1; fi

after_success:
  # Download thesis
  - wget https://pure.rug.nl/ws/files/132028374/Complete_thesis.pdf

after_failure:
  # Download thesis
  - wget https://pure.rug.nl/ws/files/132028374/Complete_thesis.pdf

